//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationalInfo
    {
        public int Eduld { get; set; }
        public string ExamPassed { get; set; }
        public string Institution { get; set; }
        public string Board { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
    }
}
