//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoResume.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResumeDB3Entities : DbContext
    {
        public ResumeDB3Entities()
            : base("name=ResumeDB3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Declartaion> Declartaions { get; set; }
        public virtual DbSet<EducationalInfo> EducationalInfoes { get; set; }
        public virtual DbSet<Objective> Objectives { get; set; }
        public virtual DbSet<Personal_Details> Personal_Details { get; set; }
        public virtual DbSet<ProjectInfo> ProjectInfoes { get; set; }
        public virtual DbSet<Summary> Summaries { get; set; }
        public virtual DbSet<TechnicalInfo> TechnicalInfoes { get; set; }
        public virtual DbSet<WorkExperience> WorkExperiences { get; set; }
    }
}
