//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal_Details
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public string ContactNo { get; set; }
        public string Nationality { get; set; }
        public string ShortAddress { get; set; }
        public string FatherName { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public string Hobby { get; set; }
        public string LanguageName { get; set; }
        public string MaritalStatus { get; set; }
        public string PerPhoto { get; set; }
        public string Profile { get; set; }
        public string PerSignature { get; set; }
        public string Place { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
    }
}
