//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectInfo
    {
        public int ProjectId { get; set; }
        public string ProjectName { get; set; }
        public string ProjectRole { get; set; }
        public Nullable<int> TeamSize { get; set; }
        public string Duration { get; set; }
        public string ProjectDescription { get; set; }
    }
}
