//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoResume.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Summary
    {
        public int ProfId { get; set; }
        public string Details1 { get; set; }
        public string Details2 { get; set; }
    }
}
